# Generated by Django 6.0.2 on 2026-03-01 21:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Billá Burger', max_length=200, verbose_name='Nome da Loja')),
                ('slogan', models.CharField(default='Os melhores hambúrgueres da cidade!', max_length=500, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('font', models.CharField(default='Google Sans', max_length=100, verbose_name='Fonte')),
                ('font_size', models.IntegerField(default=16, verbose_name='Tamanho da Fonte')),
                ('primary_color', models.CharField(default='#ef4444', max_length=20, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#fbbf24', max_length=20, verbose_name='Cor Secundária')),
                ('background_color', models.CharField(default='#f8f9fa', max_length=20, verbose_name='Cor de Fundo')),
                ('text_color', models.CharField(default='#1e293b', max_length=20, verbose_name='Cor do Texto')),
                ('pix_key', models.CharField(blank=True, max_length=200, verbose_name='Chave PIX')),
            ],
            options={
                'verbose_name': 'Configurações',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='🍽️', max_length=10, verbose_name='Emoji/Ícone')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('garcom', 'Garçom'), ('cozinha', 'Cozinha'), ('gerente', 'Gerente')], default='garcom', max_length=20, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(max_length=50, verbose_name='Mesa')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('cozinha', 'Na Cozinha'), ('pronto', 'Pronto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='cozinha', max_length=20, verbose_name='Status')),
                ('order_type', models.CharField(choices=[('dine-in', 'Mesa'), ('delivery', 'Delivery')], default='dine-in', max_length=20, verbose_name='Tipo')),
                ('address', models.TextField(blank=True, verbose_name='Endereço de Entrega')),
                ('payment_method', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], max_length=20, verbose_name='Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Garçom')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('icon', models.CharField(default='🍽️', max_length=10, verbose_name='Emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurante.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurante.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
