# Generated by Django 5.2.12 on 2026-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_ingredient_productingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_ingredient_stock',
            field=models.BooleanField(default=False, verbose_name='Controlar por ingredientes'),
        ),
    ]
