# Generated by Django 6.0.3 on 2026-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_ingredient_ingredient_stock_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade/UF'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pix_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do titular PIX'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_pix_on_receipt',
            field=models.BooleanField(default=True, verbose_name='Mostrar QR Code PIX na nota'),
        ),
    ]
