# Generated by Django 6.0.3 on 2026-03-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_appsettings_pix_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='low_stock_alert',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Alerta de estoque baixo'),
        ),
    ]
