# Generated by Django 5.2.12 on 2026-03-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_product_use_ingredient_stock'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='ingredient_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='ingredient_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('pending_quantity__gte', 0)), name='orderitem_pending_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('pending_quantity__lte', models.F('quantity'))), name='orderitem_pending_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='orderitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recipe_quantity_positive'),
        ),
    ]
