# Generated by Django 6.0.3 on 2026-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_add_receipt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='QR Code PIX'),
        ),
    ]
