# Generated by Django 6.0.3 on 2026-03-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_appsettings_pix_qrcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID do objeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Dados extras')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de abertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de fechamento')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor esperado')),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferença')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('consumo', 'Consumo'), ('ajuste', 'Ajuste'), ('perda', 'Perda'), ('estorno', 'Estorno')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('quantity_before', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque antes')),
                ('quantity_after', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque depois')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='restaurante.ingredient', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Movimentação de Ingrediente',
                'verbose_name_plural': 'Movimentações de Ingredientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
