# Generated by Django 5.2.12 on 2026-03-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_cashsession_auditlog_ingredientstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='low_stock_alert',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Alerta de estoque baixo'),
        ),
    ]
