# Generated by Django 6.0.3 on 2026-03-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0010_ingredient_low_stock_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.additional', verbose_name='Adicional')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='restaurante.orderitem', verbose_name='Item do Pedido')),
            ],
            options={
                'verbose_name': 'Adicional do Item',
                'verbose_name_plural': 'Adicionais do Item',
            },
        ),
        migrations.CreateModel(
            name='ProductAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='restaurante.additional', verbose_name='Adicional')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_additionals', to='restaurante.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Adicional do Produto',
                'verbose_name_plural': 'Adicionais do Produto',
                'unique_together': {('product', 'additional')},
            },
        ),
    ]
